/**/
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./lib/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./lib/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./lib/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./lib/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./lib/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./lib/components/icons/IconTooling.vue')['default']
    TheWelcome: typeof import('./lib/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./lib/components/WelcomeItem.vue')['default']
  }
}
