import { repoUrl } from "../../config.js";
import { default as packageJson } from '../../package.json' with { type: 'json' };
import { getBaseTags } from "./baseTags.js";
import { getFrameworksTools } from "./frameworksTools.js";
const repoTreeUrl = `${repoUrl}/tree/${packageJson.version}`;
export const baseTags = getBaseTags(repoTreeUrl);
export const frameworksTools = getFrameworksTools(repoTreeUrl);
export * from "../../config.js";
export * from "./commanderOptions.js";
export * from "./baseTags.js";
export * from "./frameworksTools.js";
export * from "./userConfig.js";
export * from "./vue.js";
export { packageJson, repoTreeUrl };
